#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2023 Jolla Ltd.
# SPDX-FileCopyrightText: 2024 - 2025 Jolla Mobile Ltd
#
# SPDX-License-Identifier: BSD-3-Clause

# Removes obsolete legacy Weather data
OLD_PATH="$HOME/.local/share/sailfish-weather"
OBSOLETE_FILE="$HOME/.local/share/org.sailfishos/weather/weather.json"

if [ -f "$OBSOLETE_FILE" ]
then
    rm -f "$OBSOLETE_FILE"
fi

if [ -d "$OLD_PATH" ]
then
    rmdir "$OLD_PATH" 2>/dev/null || :
fi
