#!/bin/sh

# SPDX-FileCopyrightText: 2020 - 2023 Jolla Ltd.
# SPDX-FileCopyrightText: 2024 - 2025 Jolla Mobile Ltd
#
# SPDX-License-Identifier: BSD-3-Clause

# Moves Weather data to new location
OLD_PATH="$HOME/.local/share/sailfish-weather"
NEW_PATH="$HOME/.local/share/org.sailfishos/weather"

if [ -e "$OLD_PATH/" ] && [ ! -e "$NEW_PATH/" ]
then
    mkdir -p "$NEW_PATH"
    if mv "$OLD_PATH/"weather.json "$NEW_PATH/"
    then
        rmdir "$OLD_PATH"
    fi
fi
